name: screw-defect-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pip:
      - tensorflow
      - transformers
      - gymnasium
      - kaggle
      - opencv-python
